name: Deploy Site

on: [push]

jobs:
  build-website:
    name: Website build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Generate assets
        run: yarn --no-bin-links && yarn dist
      - name: Build fork
        if: ${{ github.repository_owner != 'sfzformat' }}
        run: |
          bundle exec jekyll build \
            --destination public/  \
            --baseurl "/$(echo '${{ github.repository }}' | cut -d/ -f2)"
      - name: Build sfzformat
        if: ${{ github.repository_owner == 'sfzformat' }}
        run: bundle exec jekyll build --destination public/
      - name: Upload to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: www
          publish_dir: ./public
